### ISSUE TITLE
Use Separate File for Each Record

### ISSUE THREAD

**Issue by emptymalei** [kausalflow/kirsche#3]
## Why

We are currently using a single json file for all the records. This brings in some problems:

1. It is tedious to update the records inside the file.
2. Updating the list is potentially dangerous for the existing records.

Since the references of the papers won't change, we are very likely to reuse previously downloaded records and update if we do not already have the record.

This makes it an easy choice to just use multi-file based storage.

## Todo

- [x] Build a function to handle different scenarios of storage, single file or multi file.
- [x] Implement in the modules
- [x] Implement in the command line tool

- [x] ~~Save on each download~~ Stop trying if getting a lot of connection errors.

**Comment by emptymalei** [comment]
#4
